export const mockOrganization = {
  id: 'org_001',
  name: 'Global Green Energy Solutions',
  email: 'info@greenenergy.com',
  logo: 'GG',
  createdAt: new Date('2023-06-15'),
  address: '123 Sustainability Lane, San Francisco, CA 94105',
};

export const mockUsers = [
  {
    id: 'user_001',
    name: 'John Doe',
    email: 'john@carbonflow.com',
    role: 'Admin',
    avatar: 'J',
  },
  {
    id: 'user_002',
    name: 'Sarah Chen',
    email: 'sarah@carbonflow.com',
    role: 'Manager',
    avatar: 'S',
  },
  {
    id: 'user_003',
    name: 'Michael Johnson',
    email: 'michael@carbonflow.com',
    role: 'Officer',
    avatar: 'M',
  },
  {
    id: 'user_004',
    name: 'Emma Wilson',
    email: 'emma@carbonflow.com',
    role: 'Auditor',
    avatar: 'E',
  },
];

export const mockProjects = [
  {
    id: 'proj_001',
    name: 'Solar Farm Expansion - Phase 2',
    description: 'Large-scale solar energy project in California',
    status: 'Active',
    createdAt: new Date('2023-06-15'),
    location: 'Kern County, CA',
    type: 'Solar Energy',
    creditsGenerated: 125000,
    creditsVerified: 95000,
    creditsSold: 80000,
    creditsRetired: 15000,
    annualEmissionReduction: 450000, // tCO2e
    jobsCreated: 245,
    households: 38500,
    treesPlanted: 125000,
    landRestored: 1250, // hectares
    womenBeneficiaries: 120,
    youthBeneficiaries: 340,
    projectRevenue: 2400000, // USD
    riskScore: 15,
    readinessScore: 92,
  },
  {
    id: 'proj_002',
    name: 'Reforestation Initiative - Amazon Basin',
    description: 'Forest conservation and reforestation in the Amazon',
    status: 'Verification',
    createdAt: new Date('2023-08-20'),
    location: 'Amazonas, Brazil',
    type: 'Reforestation',
    creditsGenerated: 850000,
    creditsVerified: 0,
    creditsSold: 0,
    creditsRetired: 0,
    annualEmissionReduction: 280000,
    jobsCreated: 1200,
    households: 45000,
    treesPlanted: 2500000,
    landRestored: 8500,
    womenBeneficiaries: 450,
    youthBeneficiaries: 890,
    projectRevenue: 1800000,
    riskScore: 28,
    readinessScore: 65,
  },
  {
    id: 'proj_003',
    name: 'Wind Energy Park - Northern Europe',
    description: 'Offshore wind farm generating clean renewable energy',
    status: 'Issued',
    createdAt: new Date('2023-04-10'),
    location: 'North Sea, Denmark',
    type: 'Wind Energy',
    creditsGenerated: 650000,
    creditsVerified: 650000,
    creditsSold: 520000,
    creditsRetired: 130000,
    annualEmissionReduction: 380000,
    jobsCreated: 380,
    households: 52000,
    treesPlanted: 450000,
    landRestored: 350,
    womenBeneficiaries: 95,
    youthBeneficiaries: 210,
    projectRevenue: 3100000,
    riskScore: 12,
    readinessScore: 98,
  },
  {
    id: 'proj_004',
    name: 'Methane Capture - Livestock Operations',
    description: 'Biogas energy from agricultural waste',
    status: 'Draft',
    createdAt: new Date('2023-11-05'),
    location: 'Iowa, USA',
    type: 'Methane Reduction',
    creditsGenerated: 125000,
    creditsVerified: 0,
    creditsSold: 0,
    creditsRetired: 0,
    annualEmissionReduction: 95000,
    jobsCreated: 45,
    households: 8500,
    treesPlanted: 0,
    landRestored: 0,
    womenBeneficiaries: 18,
    youthBeneficiaries: 42,
    projectRevenue: 580000,
    riskScore: 35,
    readinessScore: 42,
  },
  {
    id: 'proj_005',
    name: 'Urban Green Spaces - East Africa',
    description: 'Urban reforestation and green infrastructure',
    status: 'Active',
    createdAt: new Date('2023-07-12'),
    location: 'Kenya, Uganda, Tanzania',
    type: 'Urban Reforestation',
    creditsGenerated: 280000,
    creditsVerified: 210000,
    creditsSold: 175000,
    creditsRetired: 35000,
    annualEmissionReduction: 125000,
    jobsCreated: 680,
    households: 28500,
    treesPlanted: 850000,
    landRestored: 420,
    womenBeneficiaries: 320,
    youthBeneficiaries: 580,
    projectRevenue: 950000,
    riskScore: 22,
    readinessScore: 78,
  },
  {
    id: 'proj_006',
    name: 'Geothermal Plant - Iceland',
    description: 'Renewable geothermal energy generation',
    status: 'Active',
    createdAt: new Date('2023-05-18'),
    location: 'Southwest Iceland',
    type: 'Geothermal',
    creditsGenerated: 450000,
    creditsVerified: 450000,
    creditsSold: 360000,
    creditsRetired: 90000,
    annualEmissionReduction: 320000,
    jobsCreated: 120,
    households: 32000,
    treesPlanted: 200000,
    landRestored: 180,
    womenBeneficiaries: 55,
    youthBeneficiaries: 125,
    projectRevenue: 2100000,
    riskScore: 18,
    readinessScore: 85,
  },
];

export const mockDocuments = [
  {
    id: 'doc_001',
    projectId: 'proj_001',
    name: 'Project Design Document (PDD)',
    category: 'Technical',
    uploadDate: new Date('2023-06-20'),
    size: 2.4,
    status: 'Verified',
  },
  {
    id: 'doc_002',
    projectId: 'proj_001',
    name: 'Environmental Impact Assessment',
    category: 'Environmental',
    uploadDate: new Date('2023-06-22'),
    size: 1.8,
    status: 'Verified',
  },
  {
    id: 'doc_003',
    projectId: 'proj_001',
    name: 'Community Consultation Report',
    category: 'Social',
    uploadDate: new Date('2023-06-25'),
    size: 3.2,
    status: 'Verified',
  },
  {
    id: 'doc_004',
    projectId: 'proj_002',
    name: 'Baseline and Monitoring Report',
    category: 'Monitoring',
    uploadDate: new Date('2023-09-01'),
    size: 4.1,
    status: 'Pending Review',
  },
  {
    id: 'doc_005',
    projectId: 'proj_002',
    name: 'Land Ownership Documentation',
    category: 'Legal',
    uploadDate: new Date('2023-08-25'),
    size: 2.9,
    status: 'Verified',
  },
];

export const mockRiskAssessments = [
  {
    projectId: 'proj_001',
    overallScore: 15,
    documentation: { score: 10, status: 'Low Risk' },
    compliance: { score: 18, status: 'Low Risk' },
    operational: { score: 15, status: 'Low Risk' },
    community: { score: 20, status: 'Low Risk' },
    dataQuality: { score: 12, status: 'Low Risk' },
    recommendations: [
      'Update annual monitoring report',
      'Enhance community engagement documentation',
    ],
  },
  {
    projectId: 'proj_002',
    overallScore: 28,
    documentation: { score: 35, status: 'Medium Risk' },
    compliance: { score: 25, status: 'Low Risk' },
    operational: { score: 28, status: 'Medium Risk' },
    community: { score: 32, status: 'Medium Risk' },
    dataQuality: { score: 22, status: 'Low Risk' },
    recommendations: [
      'Secure comprehensive land titles',
      'Implement enhanced monitoring systems',
      'Expand stakeholder consultation',
      'Complete missing impact assessments',
    ],
  },
];

export const mockActivityFeed = [
  {
    id: 'act_001',
    projectId: 'proj_001',
    type: 'Status Change',
    message: 'Project status updated to Active',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    user: 'John Doe',
  },
  {
    id: 'act_002',
    projectId: 'proj_001',
    type: 'Document Upload',
    message: 'Annual Monitoring Report uploaded',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    user: 'Sarah Chen',
  },
  {
    id: 'act_003',
    projectId: 'proj_003',
    type: 'Credits Issued',
    message: '650,000 credits issued and verified',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    user: 'System',
  },
  {
    id: 'act_004',
    projectId: 'proj_002',
    type: 'Comment',
    message: 'Awaiting verification from third-party auditor',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    user: 'Michael Johnson',
  },
];

export const mockKPIs = {
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter((p) => p.status === 'Active').length,
  readinessScore: 78, // Average
  totalCreditsGenerated: mockProjects.reduce((sum, p) => sum + p.creditsGenerated, 0),
  totalCreditsVerified: mockProjects.reduce((sum, p) => sum + p.creditsVerified, 0),
  totalCreditsSold: mockProjects.reduce((sum, p) => sum + p.creditsSold, 0),
  totalRevenue: mockProjects.reduce((sum, p) => sum + p.projectRevenue, 0),
  totalRisks: mockProjects.filter((p) => p.riskScore > 25).length,
  totalJobsCreated: mockProjects.reduce((sum, p) => sum + p.jobsCreated, 0),
  totalEmissionReduction: mockProjects.reduce((sum, p) => sum + p.annualEmissionReduction, 0),
  totalImpact: {
    jobs: mockProjects.reduce((sum, p) => sum + p.jobsCreated, 0),
    households: mockProjects.reduce((sum, p) => sum + p.households, 0),
    trees: mockProjects.reduce((sum, p) => sum + p.treesPlanted, 0),
    land: mockProjects.reduce((sum, p) => sum + p.landRestored, 0),
    women: mockProjects.reduce((sum, p) => sum + p.womenBeneficiaries, 0),
    youth: mockProjects.reduce((sum, p) => sum + p.youthBeneficiaries, 0),
  },
};
